In [6]:
import numpy as np


In [7]:
array = [[1,2,3],[4,5,6]]
first_array = np.array(array)
print("Array Type: {}".format(type(first_array))) 
print("Array Shape: {}".format(np.shape(first_array))) 
print(first_array)

Array Type: <class 'numpy.ndarray'>
Array Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [24]:
arr = [[3, 4], [8, 5]]   
pyTensor = torch.Tensor(arr)  
print(pyTensor)       

tensor([[3., 4.],
        [8., 5.]])


In [23]:
import torch

tensor = torch.Tensor(array)
print("Array Type: {}".format(tensor.type)) # type
print("Array Shape: {}".format(tensor.shape)) # shape
print(tensor)

Array Type: <built-in method type of Tensor object at 0x00000241785A0D68>
Array Shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [25]:
ones_t = torch.ones((2, 2))   
torch.manual_seed(0)    
rand_t = torch.rand((2, 2))  
print(ones_t)  
print(rand_t)  

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])


In [26]:
import numpy as np1  
numpy_arr = np1.ones((2, 2))  
pyTensor = torch.from_numpy(numpy_arr)  
np1_arr_from_Tensor = pyTensor.numpy()  
print(np1_arr_from_Tensor)  

[[1. 1.]
 [1. 1.]]


In [49]:
import torch  
Tensor_a = torch.ones((2, 2))  
Tensor_b = torch.ones((2, 2))  
result=Tensor_a+Tensor_b  
result1 = torch.add(Tensor_a, Tensor_b)     
Tensor_a.add_(Tensor_b) 
print(result)  
print(result1)  
print(Tensor_a)  

tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [39]:
import torch

tensor = torch.Tensor(array)
print("Array Type: {}".format(tensor.type)) 
print("Array Shape: {}".format(tensor.shape))
print(tensor)


Array Type: <built-in method type of Tensor object at 0x00000241785DD1D8>
Array Shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [42]:
print("Numpy {}\n".format(np.ones((2,3))))


Numpy [[1. 1. 1.]
 [1. 1. 1.]]



In [43]:
print("Numpy {}\n".format(np.random.rand(2,3)))

print(torch.rand(2,3))

Numpy [[0.00538451 0.84203306 0.84021281]
 [0.56322407 0.36912854 0.68780444]]

tensor([[0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323]])


In [44]:
x = torch.empty([5, 3])
print(x)

tensor([[5.1207e+33, 8.0855e-43, 5.1207e+33],
        [8.0855e-43, 5.1196e+33, 8.0855e-43],
        [5.1196e+33, 8.0855e-43, 5.1205e+33],
        [8.0855e-43, 5.1205e+33, 8.0855e-43],
        [5.1198e+33, 8.0855e-43, 5.1198e+33]])


In [45]:
y = torch.empty(5, 3)
print(y)

tensor([[9.5511e-39, 5.1429e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39]])


In [46]:
a = torch.ones(2, 3)
b = a.numpy()
print(b)
a = a.add_(1)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[2., 2., 2.],
        [2., 2., 2.]])
[[2. 2. 2.]
 [2. 2. 2.]]


In [75]:
import torch
import numpy as np 
e = d
e.add_(c)
print(e)

NameError: name 'd' is not defined

In [66]:
import numpy as np
a = np.ones((5, 2))
b = torch.from_numpy(a) ## This is the command
print(b)
np.add(a, 3, out = a)
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]
tensor([[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]], dtype=torch.float64)
